services:
  account-service:
    build:
      context: .
    container_name: account
    image: account-service
    environment:
      DB_HOST: db
    ports:
      - "1400:1400"
    networks:
      - backend

networks:
  backend:
    external: true