// Code generated by mockery v2.41.0. DO NOT EDIT.

package mocks

import (
	port "account-service/internal/core/port"

	mock "github.com/stretchr/testify/mock"
)

// TransactionRepo is an autogenerated mock type for the TransactionRepo type
type TransactionRepo struct {
	mock.Mock
}

// GetByUserId provides a mock function with given fields: userId
func (_m *TransactionRepo) GetByUserId(userId string) ([]port.Transaction, error) {
	ret := _m.Called(userId)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserId")
	}

	var r0 []port.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]port.Transaction, error)); ok {
		return rf(userId)
	}
	if rf, ok := ret.Get(0).(func(string) []port.Transaction); ok {
		r0 = rf(userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]port.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTransactionRepo creates a new instance of TransactionRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionRepo {
	mock := &TransactionRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
